import { useMemo, useState } from 'react'
import './App.css'

type NavItem = { label: string; icon: string }
type FileAsset = { name: string; kind: string }
type Doctor = { id: string; name: string; color: string }
type Appointment = { id: string; patientId: string; doctorId: string; date: string; time: string; reminder: boolean; treatment: string }
type Prescription = { medication: string; dose: string; frequency: string; duration: string; instructions: string }
type TimelineEvent = { id: string; date: string; text: string; actor: string }
type Patient = {
  initials: string; name: string; id: string; age: number; gender: string; location: string; occupation: string; reference: string; phone: string; email: string
  chiefComplaint: string; historyPresentIllness: string; medicalHistory: string; clinicalFindings: string; primaryDiagnosis: string; finalDiagnosis: string; treatmentAdvised: string
  procedure: string; status: 'Planning' | 'Review' | 'Imaging' | 'Ready'; updated: string; files: FileAsset[]; prescriptions: Prescription[]; timeline: TimelineEvent[]
}

const navItems: NavItem[] = [
  { label: 'Overview', icon: 'grid' }, { label: 'Patients', icon: 'users' }, { label: 'Imaging', icon: 'scan' }, { label: 'Planning', icon: 'layers' }, { label: 'Reports', icon: 'file' },
]
const doctors: Doctor[] = [
  { id: 'd1', name: 'Dr. Aishwarya Jain', color: 'doctor-a' }, { id: 'd2', name: 'Dr. Agarwal', color: 'doctor-b' }, { id: 'd3', name: 'Dr. Sharma', color: 'doctor-c' }, { id: 'd4', name: 'Dr. Rao', color: 'doctor-d' },
]
const hours = ['09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00']
const weekDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const initialPatients: Patient[] = [
  { initials: 'AR', name: 'Aarav Rao', id: 'SC-1024', age: 24, gender: 'Male', location: 'Hyderabad', occupation: 'Software engineer', reference: 'Dr. Mehta', phone: '+91 90000 00001', email: 'aarav@example.com', chiefComplaint: 'Difficulty chewing and facial imbalance', historyPresentIllness: 'Progressive bite discrepancy for 3 years.', medicalHistory: 'No significant medical history reported.', clinicalFindings: 'Skeletal Class III tendency; mandibular asymmetry.', primaryDiagnosis: 'Skeletal Class III malocclusion', finalDiagnosis: '', treatmentAdvised: 'Orthognathic workup', procedure: 'Orthognathic planning', status: 'Planning', updated: 'Today, 10:42', files: [], prescriptions: [], timeline: [{ id: 't1', date: '13 Aug 2026 · 10:42', text: 'Patient record created', actor: 'Dr. Aishwarya Jain' }] },
  { initials: 'MS', name: 'Meera Shah', id: 'SC-1023', age: 21, gender: 'Female', location: 'Secunderabad', occupation: 'Student', reference: 'Self', phone: '+91 90000 00002', email: 'meera@example.com', chiefComplaint: 'Crowding of lower anterior teeth', historyPresentIllness: 'Crowding noticed since adolescence.', medicalHistory: 'Nil significant.', clinicalFindings: 'Moderate anterior crowding.', primaryDiagnosis: 'Malocclusion with dental crowding', finalDiagnosis: '', treatmentAdvised: 'Follow up for aligner review', procedure: 'Aligner planning', status: 'Review', updated: 'Today, 09:18', files: [], prescriptions: [], timeline: [] },
  { initials: 'VK', name: 'Vikram Kumar', id: 'SC-1022', age: 29, gender: 'Male', location: 'Hyderabad', occupation: 'Architect', reference: 'Dr. Rao', phone: '+91 90000 00003', email: 'vikram@example.com', chiefComplaint: 'Jaw pain', historyPresentIllness: 'Intermittent preauricular pain for 6 months.', medicalHistory: 'No known allergies reported.', clinicalFindings: 'Tenderness over TMJ region.', primaryDiagnosis: 'TMJ disorder - evaluation', finalDiagnosis: '', treatmentAdvised: 'CBCT review', procedure: 'CBCT analysis', status: 'Imaging', updated: 'Yesterday', files: [{ name: 'CBCT_1022.zip', kind: 'CBCT / DICOM' }], prescriptions: [], timeline: [] },
  { initials: 'NP', name: 'Nisha Patel', id: 'SC-1021', age: 26, gender: 'Female', location: 'Hyderabad', occupation: 'Designer', reference: 'Dr. Shah', phone: '+91 90000 00004', email: 'nisha@example.com', chiefComplaint: 'Facial asymmetry', historyPresentIllness: 'Longstanding facial asymmetry.', medicalHistory: 'Nil significant.', clinicalFindings: 'Chin deviation to left.', primaryDiagnosis: 'Facial asymmetry', finalDiagnosis: 'Skeletal facial asymmetry', treatmentAdvised: 'Virtual surgical planning', procedure: 'Surgical simulation', status: 'Ready', updated: 'Yesterday', files: [], prescriptions: [], timeline: [] },
]

function Icon({ name }: { name: string }) {
  const paths: Record<string, string> = { grid: 'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', users: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75', scan: 'M8 3H5a2 2 0 0 0-2 2v3M16 3h3a2 2 0 0 1 2 2v3M21 16v3a2 2 0 0 1-2 2h-3M8 21H5a2 2 0 0 1-2-2v-3M7 8h10v8H7z', layers: 'm12 2 9 5-9 5-9-5 9-5ZM3 12l9 5 9-5M3 17l9 5 9-5', file: 'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8M8 17h6', plus: 'M12 5v14M5 12h14', bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4', search: 'm21 21-4.35-4.35M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z', arrow: 'M5 12h14M13 6l6 6-6 6', chevron: 'm9 18 6-6-6-6', close: 'M6 6l12 12M18 6 6 18', filter: 'M4 6h16M7 12h10M10 18h4', calendar: 'M7 3v4M17 3v4M4 9h16M6 5h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z', print: 'M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2M6 14h12v7H6z', save: 'M5 3h12l3 3v15H4V3h13M8 3v6h8V3', upload: 'M12 16V4M7 9l5-5 5 5M4 20h16', clock: 'M12 7v5l3 2', whatsapp: 'M6 19l1-3a7 7 0 1 1 3 3l-4 1Z', camera: 'M4 7h3l2-2h6l2 2h3v12H4zM12 16a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z' }
  return <svg viewBox="0 0 24 24" aria-hidden="true" className="icon"><path d={paths[name]} /></svg>
}

const blankPatient: Patient = { initials: '', name: '', id: '', age: 0, gender: '', location: '', occupation: '', reference: '', phone: '', email: '', chiefComplaint: '', historyPresentIllness: '', medicalHistory: '', clinicalFindings: '', primaryDiagnosis: '', finalDiagnosis: '', treatmentAdvised: '', procedure: '', status: 'Imaging', updated: 'Just now', files: [], prescriptions: [], timeline: [] }
function Field({ label, value, onChange, multiline = false, type = 'text', placeholder = '' }: { label: string; value: string | number; onChange: (v: string) => void; multiline?: boolean; type?: string; placeholder?: string }) { return <label className={multiline ? 'field field-wide' : 'field'}><span>{label}</span>{multiline ? <textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} rows={3} /> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />}</label> }

function UploadCard({ label, kind, files, onUpload, onOpen }: { label: string; kind: string; files: FileAsset[]; onUpload: (kind: string, file?: File) => void; onOpen: (kind: string) => void }) { const asset = files.find((f) => f.kind === kind); return <div className="upload-card"><div className="upload-icon"><Icon name={kind.includes('CBCT') ? 'scan' : kind.includes('STL') ? 'layers' : 'camera'} /></div><div><strong>{label}</strong><small>{asset?.name || (kind.includes('CBCT') ? 'DICOM series / ZIP' : kind.includes('STL') ? 'STL mesh' : 'JPG / PNG')}</small></div><label className="upload-button">Upload<input type="file" accept={kind.includes('CBCT') ? '.dcm,.zip' : kind.includes('STL') ? '.stl' : 'image/*'} onChange={(e) => onUpload(kind, e.target.files?.[0])} /></label>{asset && <button className="viewer-button" onClick={() => onOpen(kind)}>Open</button>}</div> }

function PatientForm({ patient, onSave, onCancel }: { patient?: Patient; onSave: (p: Patient) => void; onCancel: () => void }) {
  const [form, setForm] = useState<Patient>(patient || blankPatient); const [activeSection, setActiveSection] = useState('Clinical'); const [files, setFiles] = useState<FileAsset[]>(patient?.files || [])
  const set = (key: keyof Patient, value: string | number) => setForm((p) => ({ ...p, [key]: value }))
  const upload = (kind: string, file?: File) => { if (file) setFiles((current) => [...current.filter((f) => f.kind !== kind), { name: file.name, kind }]) }
  const save = () => { if (!form.name.trim()) return; const parts = form.name.trim().split(/\s+/); const now = new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }); const event: TimelineEvent = { id: `t-${Date.now()}`, date: now, text: patient ? 'Patient record updated' : 'Patient record created', actor: 'Dr. Aishwarya Jain' }; onSave({ ...form, initials: parts.slice(0, 2).map((x) => x[0]).join('').toUpperCase(), id: form.id || `SC-${1025 + Math.floor(Math.random() * 900)}`, age: Number(form.age) || 0, files, updated: 'Just now', timeline: [...(patient?.timeline || []), event] }) }
  const uploadOpen = (kind: string) => alert(kind.includes('CBCT') ? 'DICOM viewer integration is the next imaging step.' : kind.includes('STL') ? 'STL viewer integration is the next 3D step.' : 'Media preview will be available here.')
  const media = [['Patient photographs', 'Patient photographs'], ['OPG', 'OPG'], ['CBCT / DICOM', 'CBCT / DICOM'], ['Intraoral scan / STL', 'Intraoral scan / STL'], ['Intraoral photos', 'Intraoral photos'], ['Extraoral photos', 'Extraoral photos'], ['Pre-op photographs', 'Pre-op photographs'], ['Post-op photographs', 'Post-op photographs']]
  return <div className="form-page"><section className="page-heading"><div><p className="eyebrow">PATIENT DATA</p><h1>{patient ? `Edit ${patient.name}` : 'New patient record'}</h1><p className="subheading">Capture clinical information, media, treatment and follow-up data in one patient record.</p></div><div className="heading-actions"><button className="secondary-button" onClick={onCancel}>Cancel</button><button className="primary-button" onClick={save}><Icon name="save" />Save patient</button></div></section><div className="patient-form-tabs">{['Clinical', 'Media & scans', 'Pre-op / Post-op', 'Prescription'].map((tab) => <button className={activeSection === tab ? 'active' : ''} key={tab} onClick={() => setActiveSection(tab)}>{tab}</button>)}</div>
    {activeSection === 'Clinical' && <><section className="form-section panel"><div className="section-title"><span>01</span><div><h2>Patient information</h2><p>Demographics and contact details.</p></div></div><div className="form-grid wide"><Field label="Name *" value={form.name} onChange={(v) => set('name', v)} /><Field label="Age" type="number" value={form.age} onChange={(v) => set('age', v)} /><label className="field"><span>Gender</span><select value={form.gender} onChange={(e) => set('gender', e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><Field label="Location" value={form.location} onChange={(v) => set('location', v)} /><Field label="Occupation" value={form.occupation} onChange={(v) => set('occupation', v)} /><Field label="Reference of (if any)" value={form.reference} onChange={(v) => set('reference', v)} /><Field label="Phone number" value={form.phone} onChange={(v) => set('phone', v)} /><Field label="Email ID" type="email" value={form.email} onChange={(v) => set('email', v)} /></div></section><section className="form-section panel"><div className="section-title"><span>02</span><div><h2>Clinical history & findings</h2><p>Document the clinical encounter.</p></div></div><div className="form-grid"><Field label="Chief complaint" value={form.chiefComplaint} onChange={(v) => set('chiefComplaint', v)} multiline /><Field label="History of present illness" value={form.historyPresentIllness} onChange={(v) => set('historyPresentIllness', v)} multiline /><Field label="Medical history" value={form.medicalHistory} onChange={(v) => set('medicalHistory', v)} multiline /><Field label="Clinical findings" value={form.clinicalFindings} onChange={(v) => set('clinicalFindings', v)} multiline /><Field label="Primary diagnosis" value={form.primaryDiagnosis} onChange={(v) => set('primaryDiagnosis', v)} /><Field label="Final diagnosis" value={form.finalDiagnosis} onChange={(v) => set('finalDiagnosis', v)} /><Field label="Treatment advised" value={form.treatmentAdvised} onChange={(v) => set('treatmentAdvised', v)} multiline placeholder="This text is used on the appointment grid." /></div></section></>}
    {activeSection === 'Media & scans' && <section className="form-section panel"><div className="section-title"><span>03</span><div><h2>Imaging & clinical media</h2><p>Upload source files and images for this patient.</p></div></div><div className="upload-grid">{media.slice(0, 6).map(([label, kind]) => <UploadCard key={kind} label={label} kind={kind} files={files} onUpload={upload} onOpen={uploadOpen} />)}</div></section>}
    {activeSection === 'Pre-op / Post-op' && <section className="form-section panel"><div className="section-title"><span>04</span><div><h2>Pre-operative & post-operative photographs</h2><p>Dedicated slots for images captured from the dental chair intraoral camera.</p></div></div><div className="upload-grid">{media.slice(6).map(([label, kind]) => <UploadCard key={kind} label={label} kind={kind} files={files} onUpload={upload} onOpen={uploadOpen} />)}</div><div className="photo-note"><Icon name="camera" /><div><strong>Chairside camera workflow</strong><p>These fields are designed for future direct capture/import from compatible intraoral cameras. For now, upload the exported JPG/PNG images.</p></div></div></section>}
    {activeSection === 'Prescription' && <section className="form-section panel"><div className="section-title"><span>05</span><div><h2>Prescription</h2><p>Doctor and clinic header will come from the registered account profile.</p></div></div><PrescriptionEditor prescriptions={form.prescriptions} onChange={(prescriptions) => setForm((p) => ({ ...p, prescriptions }))} /><div className="form-actions"><button className="secondary-button" onClick={() => window.print()}><Icon name="print" />Print patient record</button><button className="primary-button" onClick={save}><Icon name="save" />Save record</button></div></section>}
  </div>
}

function PrescriptionEditor({ prescriptions, onChange }: { prescriptions: Prescription[]; onChange: (p: Prescription[]) => void }) { const add = () => onChange([...prescriptions, { medication: '', dose: '', frequency: '', duration: '', instructions: '' }]); const update = (i: number, key: keyof Prescription, value: string) => onChange(prescriptions.map((p, index) => index === i ? { ...p, [key]: value } : p)); return <div className="prescription-editor"><div className="prescription-actions"><span>Doctor and clinic header: <b>configured after registration</b></span><button className="secondary-button" onClick={add}><Icon name="plus" />Add medicine</button></div>{prescriptions.map((p, i) => <div className="medicine-row" key={i}><input placeholder="Medicine" value={p.medication} onChange={(e) => update(i, 'medication', e.target.value)} /><input placeholder="Dose" value={p.dose} onChange={(e) => update(i, 'dose', e.target.value)} /><input placeholder="Frequency" value={p.frequency} onChange={(e) => update(i, 'frequency', e.target.value)} /><input placeholder="Duration" value={p.duration} onChange={(e) => update(i, 'duration', e.target.value)} /><input placeholder="Instructions" value={p.instructions} onChange={(e) => update(i, 'instructions', e.target.value)} /></div>)}{!prescriptions.length && <div className="empty-state">No medicines added yet.</div>}</div> }

function PatientProfile({ patient, onBack, onEdit, onPrescription }: { patient: Patient; onBack: () => void; onEdit: () => void; onPrescription: () => void }) { return <div className="profile-page"><section className="page-heading"><div><button className="text-button" onClick={onBack}>← Patients</button><p className="eyebrow">PATIENT PROFILE</p><h1>{patient.name}</h1><p className="subheading">{patient.id} · {patient.age} years · {patient.gender} · {patient.procedure}</p></div><div className="heading-actions"><button className="secondary-button" onClick={() => window.print()}><Icon name="print" />Print</button><button className="secondary-button" onClick={onPrescription}>Prescription</button><button className="primary-button" onClick={onEdit}>Edit patient</button></div></section><section className="profile-grid"><article className="panel profile-card"><div className="panel-header"><div><p className="eyebrow">CLINICAL SUMMARY</p><h2>Patient information</h2></div></div><dl className="detail-list"><dt>Location</dt><dd>{patient.location || '—'}</dd><dt>Occupation</dt><dd>{patient.occupation || '—'}</dd><dt>Reference</dt><dd>{patient.reference || '—'}</dd><dt>Phone</dt><dd>{patient.phone || '—'}</dd><dt>Email</dt><dd>{patient.email || '—'}</dd><dt>Chief complaint</dt><dd>{patient.chiefComplaint || '—'}</dd><dt>Primary diagnosis</dt><dd>{patient.primaryDiagnosis || '—'}</dd><dt>Final diagnosis</dt><dd>{patient.finalDiagnosis || '—'}</dd><dt>Treatment advised</dt><dd>{patient.treatmentAdvised || '—'}</dd></dl></article><article className="panel timeline-card"><div className="panel-header"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Clinical timeline</h2></div></div><div className="timeline">{patient.timeline.length ? patient.timeline.slice().reverse().map((e) => <div key={e.id}><span className="timeline-dot" /><div><strong>{e.text}</strong><p>{e.date} · {e.actor}</p></div></div>) : <div className="empty-state">No timeline events yet.</div>}</div></article></section></div> }

function PrescriptionPage({ patient, onBack }: { patient: Patient; onBack: () => void }) { return <div className="prescription-page"><section className="page-heading no-print"><div><button className="text-button" onClick={onBack}>← Patient profile</button><p className="eyebrow">PRESCRIPTION</p><h1>Prescription for {patient.name}</h1></div><div className="heading-actions"><button className="secondary-button" onClick={() => window.print()}><Icon name="print" />Print</button><button className="primary-button" onClick={() => alert('Prescription saved in the patient record.') }><Icon name="save" />Save</button></div></section><article className="print-sheet"><header className="prescription-header"><div><h2>Dr. __________________________</h2><p>Hospital / Clinic: __________________________</p><p>Address: ___________________________________</p><p>Website: __________________ · Email: __________________</p></div><div className="rx">Rx</div></header><hr /><section className="prescription-patient"><strong>{patient.name}</strong><span>{patient.id} · {patient.age} years · {patient.gender}</span><span>Date: {new Date().toLocaleDateString('en-IN')}</span></section>{patient.prescriptions.map((p, i) => <div className="prescription-line" key={i}><b>{i + 1}. {p.medication || 'Medicine'}</b><span>{p.dose} · {p.frequency} · {p.duration}</span><small>{p.instructions}</small></div>)}{!patient.prescriptions.length && <div className="empty-state">No medicines prescribed.</div>}<footer>Doctor signature: __________________________</footer></article></div> }

function startOfWeek(value: Date) { const d = new Date(value); const day = d.getDay(); const diff = day === 0 ? -6 : 1 - day; d.setDate(d.getDate() + diff); d.setHours(0, 0, 0, 0); return d }
function isoDate(d: Date) { return d.toISOString().slice(0, 10) }
function formatWeekLabel(start: Date) { const end = new Date(start); end.setDate(start.getDate() + 6); return `${start.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} – ${end.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}` }

function WeeklyAppointments({ appointments, patients, onBook, onPatient }: { appointments: Appointment[]; patients: Patient[]; onBook: (date: string, time: string) => void; onPatient: (p: Patient) => void }) {
  const [weekStart, setWeekStart] = useState(startOfWeek(new Date()))
  const [doctorFilter, setDoctorFilter] = useState('All')
  const days = useMemo(() => weekDays.map((_, i) => { const d = new Date(weekStart); d.setDate(weekStart.getDate() + i); return d }), [weekStart])
  const patientFor = (id: string) => patients.find((p) => p.id === id)
  const getAppointment = (date: string, time: string) => appointments.find((a) => a.date === date && a.time === time && (doctorFilter === 'All' || a.doctorId === doctorFilter))
  const moveWeek = (amount: number) => { const d = new Date(weekStart); d.setDate(d.getDate() + amount * 7); setWeekStart(d) }
  return <article className="panel appointment-panel"><div className="appointment-toolbar"><div><p className="eyebrow">TEAM SCHEDULE</p><h2>Appointments</h2><span>{formatWeekLabel(weekStart)}</span></div><div className="appointment-controls"><button className="icon-button" onClick={() => moveWeek(-1)}>‹</button><button className="secondary-button" onClick={() => setWeekStart(startOfWeek(new Date()))}>This week</button><button className="icon-button" onClick={() => moveWeek(1)}>›</button><label className="week-picker"><Icon name="calendar" /><input type="date" value={isoDate(weekStart)} onChange={(e) => e.target.value && setWeekStart(startOfWeek(new Date(`${e.target.value}T00:00:00`)))} /></label><select value={doctorFilter} onChange={(e) => setDoctorFilter(e.target.value)}><option value="All">All doctors</option>{doctors.map((d) => <option value={d.id} key={d.id}>{d.name}</option>)}</select></div></div><div className="doctor-legend">{doctors.map((d) => <span key={d.id}><i className={d.color} />{d.name}</span>)}</div><div className="schedule-scroll"><div className="schedule-grid"><div className="time-head">Time</div>{days.map((d) => <div className="day-head" key={isoDate(d)}><strong>{weekDays[d.getDay() === 0 ? 6 : d.getDay() - 1]}</strong><span>{d.getDate()} {d.toLocaleDateString('en-IN', { month: 'short' })}</span></div>)}{hours.map((time) => <div className="schedule-row" key={time}><div className="time-cell">{time}</div>{days.map((d) => { const date = isoDate(d); const appointment = getAppointment(date, time); const patient = appointment && patientFor(appointment.patientId); const doctor = appointment && doctors.find((x) => x.id === appointment.doctorId); return <button key={`${date}-${time}`} className={`slot ${appointment ? doctor?.color || '' : ''}`} onClick={() => appointment && patient ? onPatient(patient) : onBook(date, time)}>{appointment && patient ? <><strong>{patient.name}</strong><span>{appointment.treatment || 'Checkup'}</span><small>{doctor?.name.replace('Dr. ', 'Dr. ')}</small></> : <span className="slot-plus">+</span>}</button>})}</div>)}</div></div></article>
}

function Dashboard({ patients, appointments, onNewPatient, onBook, onPatient }: { patients: Patient[]; appointments: Appointment[]; onNewPatient: () => void; onBook: (date: string, time: string) => void; onPatient: (p: Patient) => void }) { return <><section className="page-heading"><div><p className="eyebrow">THURSDAY, 13 AUGUST 2026</p><h1>Good afternoon, Dr. Jain.</h1><p className="subheading">Your surgical planning workspace is ready.</p></div><button className="primary-button" onClick={onNewPatient}><Icon name="plus" />New patient</button></section><section className="stats-grid"><article className="stat-card"><span>Active patients</span><strong>{patients.length}</strong><small><b>+3</b> this month</small></article><article className="stat-card"><span>Plans in progress</span><strong>{patients.filter((p) => p.status === 'Planning').length + 5}</strong><small><b>3</b> need review</small></article><article className="stat-card"><span>Imaging studies</span><strong>42</strong><small><b>6</b> uploaded this week</small></article><article className="stat-card accent-card"><span>Ready for simulation</span><strong>{patients.filter((p) => p.status === 'Ready').length + 4}</strong><small>Cases with complete datasets</small></article></section><WeeklyAppointments appointments={appointments} patients={patients} onBook={onBook} onPatient={onPatient} /><section className="bottom-grid"><article className="panel timeline-panel"><div className="panel-header"><div><p className="eyebrow">TODAY</p><h2>Clinical activity</h2></div></div><div className="timeline"><div><span className="timeline-dot" /><div><strong>CBCT imported</strong><p>Vikram Kumar · 09:42</p></div></div><div><span className="timeline-dot" /><div><strong>Plan marked ready</strong><p>Nisha Patel · 08:56</p></div></div></div></article><article className="panel readiness-panel"><div className="readiness-copy"><p className="eyebrow">DATA READINESS</p><h2>Build the complete patient dataset</h2><p>Combine CBCT/DICOM, intraoral scans and treatment records in one planning workspace.</p></div><div className="readiness-graphic"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-core">3D</div></div></article></section></> }

function PatientsPage({ patients, onNewPatient, onPatient }: { patients: Patient[]; onNewPatient: () => void; onPatient: (p: Patient) => void }) { const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const filtered = useMemo(() => patients.filter((p) => `${p.name} ${p.id} ${p.procedure}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || p.status === status)), [patients, query, status]); return <><section className="page-heading"><div><p className="eyebrow">PATIENT MANAGEMENT</p><h1>Patients</h1><p className="subheading">Open a patient to view the complete clinical record.</p></div><button className="primary-button" onClick={onNewPatient}><Icon name="plus" />New patient</button></section><section className="patient-toolbar panel"><div className="patient-search"><Icon name="search" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search patient name, ID or procedure" /></div><div className="filter-wrap"><Icon name="filter" /><select value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Planning</option><option>Review</option><option>Imaging</option><option>Ready</option></select></div></section><section className="panel patient-table-panel"><div className="patient-table-head"><span>Patient</span><span>Clinical workflow</span><span>Status</span><span>Updated</span></div><div className="patient-list">{filtered.map((p) => <button className="patient-row" key={p.id} onClick={() => onPatient(p)}><div className="patient-avatar">{p.initials}</div><div className="patient-main"><strong>{p.name}</strong><span>{p.id} · {p.age} yrs · {p.gender} · {p.procedure}</span></div><span className={`status status-${p.status.toLowerCase()}`}>{p.status}</span><span className="patient-date">{p.updated}</span><Icon name="chevron" /></button>)}{filtered.length === 0 && <div className="empty-state"><strong>No patients found</strong><span>Try another search or create a new patient.</span></div>}</div></section></> }

function NewAppointmentModal({ date, time, patients, onClose, onCreate }: { date: string; time: string; patients: Patient[]; onClose: () => void; onCreate: (a: Appointment) => void }) { const [patientId, setPatientId] = useState(patients[0]?.id || ''); const [doctorId, setDoctorId] = useState(doctors[0].id); const [treatment, setTreatment] = useState(''); const [reminder, setReminder] = useState(false); return <div className="modal-backdrop"><div className="modal appointment-modal"><div className="modal-header"><div><p className="eyebrow">BOOK APPOINTMENT</p><h2>{new Date(`${date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })} · {time}</h2></div><button className="icon-button" onClick={onClose}><Icon name="close" /></button></div><div className="form-grid"><label className="field"><span>Patient</span><select value={patientId} onChange={(e) => setPatientId(e.target.value)}>{patients.map((p) => <option value={p.id} key={p.id}>{p.name} · {p.id}</option>)}</select></label><label className="field"><span>Doctor</span><select value={doctorId} onChange={(e) => setDoctorId(e.target.value)}>{doctors.map((d) => <option value={d.id} key={d.id}>{d.name}</option>)}</select></label><Field label="Treatment / visit type" value={treatment} onChange={setTreatment} placeholder="e.g. Checkup, Follow up, Surgical planning" /><label className="checkbox-field"><input type="checkbox" checked={reminder} onChange={(e) => setReminder(e.target.checked)} /> Send appointment reminder</label></div><div className="modal-footer"><span>Tip: leaving treatment blank will use the patient's Treatment advised field.</span><div><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => { const p = patients.find((x) => x.id === patientId); onCreate({ id: `a-${Date.now()}`, patientId, doctorId, date, time, reminder, treatment: treatment || p?.treatmentAdvised || 'Checkup' }) }}>Book appointment</button></div></div></div></div> }

function App() { const [active, setActive] = useState('Overview'); const [patients, setPatients] = useState(initialPatients); const [appointments, setAppointments] = useState<Appointment[]>([]); const [showNew, setShowNew] = useState(false); const [showAppointment, setShowAppointment] = useState<{ date: string; time: string } | null>(null); const [selectedPatient, setSelectedPatient] = useState<Patient | null>(null); const [editing, setEditing] = useState(false); const [prescriptionView, setPrescriptionView] = useState(false)
  const savePatient = (p: Patient) => { setPatients((current) => { const exists = current.some((x) => x.id === p.id); return exists ? current.map((x) => x.id === p.id ? p : x) : [p, ...current] }); setShowNew(false); setEditing(false); setSelectedPatient(p); setActive('Patients') }
  const openPatient = (p: Patient) => { setSelectedPatient(p); setEditing(false); setPrescriptionView(false) }
  const render = () => { if (selectedPatient && prescriptionView) return <PrescriptionPage patient={selectedPatient} onBack={() => setPrescriptionView(false)} />; if (selectedPatient && editing) return <PatientForm patient={selectedPatient} onSave={savePatient} onCancel={() => setEditing(false)} />; if (selectedPatient) return <PatientProfile patient={selectedPatient} onBack={() => setSelectedPatient(null)} onEdit={() => setEditing(true)} onPrescription={() => setPrescriptionView(true)} />; if (active === 'Patients') return <PatientsPage patients={patients} onNewPatient={() => setShowNew(true)} onPatient={openPatient} />; if (active === 'Overview') return <Dashboard patients={patients} appointments={appointments} onNewPatient={() => setShowNew(true)} onBook={(date, time) => setShowAppointment({ date, time })} onPatient={openPatient} />; const title = active === 'Imaging' ? 'Imaging' : active === 'Planning' ? 'Treatment planning' : 'Reports'; const icon = active === 'Imaging' ? 'scan' : active === 'Planning' ? 'layers' : 'file'; return <section className="placeholder-page"><div className="placeholder-icon"><Icon name={icon} /></div><p className="eyebrow">{active.toUpperCase()}</p><h1>{title}</h1><p>This module is scaffolded for the DICOM viewer, STL viewer and planning engine.</p><span className="coming-soon">MODULE FOUNDATION</span></section> }
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">S</div><div><strong>SculptOS</strong><span>Clinical workspace</span></div></div><div className="workspace-label">WORKSPACE</div><nav>{navItems.map((item) => <button key={item.label} className={`nav-item ${active === item.label ? 'active' : ''}`} onClick={() => { setActive(item.label); setSelectedPatient(null) }}><Icon name={item.icon} /><span>{item.label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Icon name="file" /><span>Settings</span></button><div className="user-card"><div className="avatar">AJ</div><div className="user-copy"><strong>Dr. Aishwarya Jain</strong><span>Maxillofacial Surgery</span></div><Icon name="chevron" /></div></div></aside><main className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{selectedPatient ? selectedPatient.name : active}</strong></div><div className="topbar-actions"><button className="icon-button"><Icon name="search" /></button><button className="icon-button notification"><Icon name="bell" /><span /></button><div className="mini-avatar">AJ</div></div></header><div className="content">{render()}</div></main>{showNew && <div className="modal-backdrop"><div className="modal large-modal"><PatientForm onSave={savePatient} onCancel={() => setShowNew(false)} /></div></div>}{showAppointment && <NewAppointmentModal date={showAppointment.date} time={showAppointment.time} patients={patients} onClose={() => setShowAppointment(null)} onCreate={(a) => { setAppointments((x) => [...x, a]); setShowAppointment(null) }} />}</div> }

export default App
